version: '2'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    # env_file:
    #   - ./postgres/postgres.env
  redis:
    build: ./redis
    ports:
      - '6379:6379'
    env_file:
      - ./redis/redis.env
