# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e9a2835f9d120f7cd0d352968caf0544ba66025cebe9ff524a3f991f9eabf9436edd40b769052c57222a76b26e8fb74b329c066a5617e99cf5dfd6419e1fc79

test:
  secret_key_base: c01115cec05f4ee84bd52215b340f8b1f6235d9b0a69e454ca9cf301e8a62d2bcc643088f05f1981a3db7fea813a9deca2996be1c3a9d1317a98459c78545c67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
